# https://taskfile.dev

version: "2"

vars:
  REGISTRY: registry.docker.com
  OWNER: adrfranklin
  SERVICE: alpine-samp
  GIT_COMMIT: { sh: git describe --always --dirty --tags }

tasks:
  build:
    cmds:
      - docker build -t {{.SERVICE}} .

  push:
    deps: ["build"]
    cmds:
      - docker tag {{.SERVICE}} {{.OWNER}}/{{.SERVICE}}:{{.GIT_COMMIT}}
      - docker push {{.OWNER}}/{{.SERVICE}}:{{.GIT_COMMIT}}
      - docker tag {{.SERVICE}} {{.OWNER}}/{{.SERVICE}}:latest
      - docker push {{.OWNER}}/{{.SERVICE}}:latest
